const cuisinesList = [
  { id: 0, cuisine: "American" },
  { id: 1, cuisine: "BBQ" },
  { id: 2, cuisine: "Burgers" },
  { id: 3, cuisine: "Cafe" },
  { id: 4, cuisine: "Chinese" },
  { id: 5, cuisine: "Desserts" },
  { id: 6, cuisine: "French" },
  { id: 7, cuisine: "Greek" },
  { id: 8, cuisine: "Healthy" },
  { id: 9, cuisine: "Indian" },
  { id: 10, cuisine: "Italian" },
  { id: 11, cuisine: "Japanese" },
  { id: 12, cuisine: "Mexican" },
  { id: 13, cuisine: "Noodles" },
  { id: 14, cuisine: "Organic" },
  { id: 15, cuisine: "Pasta" },
  { id: 16, cuisine: "Pizza" },
  { id: 17, cuisine: "Salads" },
  { id: 18, cuisine: "Seafood" },
  { id: 19, cuisine: "Spanish" },
  { id: 20, cuisine: "Steak" },
  { id: 21, cuisine: "Sushi" },
  { id: 22, cuisine: "Tacos" },
  { id: 23, cuisine: "Tapas" },
  { id: 24, cuisine: "Vegan" },
];

export { cuisinesList };
